# Generated by Django 5.1 on 2024-08-20 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_simple', models.CharField(max_length=100)),
                ('name_complex', models.CharField(max_length=100)),
                ('name_arabic', models.CharField(max_length=100)),
                ('revelation_place', models.CharField(max_length=50)),
                ('revelation_order', models.IntegerField()),
                ('bismillah_pre', models.BooleanField()),
                ('verses_count', models.IntegerField()),
                ('pages', models.JSONField()),
                ('translated_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('juz_number', models.IntegerField()),
                ('first_verse_id', models.IntegerField()),
                ('last_verse_id', models.IntegerField()),
                ('verses_count', models.IntegerField()),
                ('verse_mapping', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='QuranWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_id', models.IntegerField()),
                ('verse_key', models.CharField(max_length=10)),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.chapter')),
                ('juz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.juz')),
            ],
        ),
    ]
