# Generated by Django 5.1 on 2024-08-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juz',
            name='juz_number',
            field=models.PositiveIntegerField(),
        ),
    ]
